name: CI/CD Pipeline EKS Innovatech

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: innovatech-cluster  # <--- ¡CORREGIDO AQUÍ! Mismo nombre de tu clúster real

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout del codigo fuente
      uses: actions/checkout@v3

    - name: 2. Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 3. Iniciar sesion en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: 4. Build y Push - Backend Despachos
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: back-despachos
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO[cite: 2]
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: 5. Build y Push - Backend Ventas
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: back-ventas
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./back-Ventas_SpringBoot/Springboot-API-REST[cite: 2]
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: 6. Build y Push - Frontend React
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: front-despacho
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./front_despacho[cite: 2]
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: 7. Actualizar Kubeconfig y Desplegar en AWS EKS
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
        kubectl apply -f k8s/[cite: 2]
        kubectl rollout restart deployment/back-despachos
        kubectl rollout restart deployment/back-ventas
        kubectl rollout restart deployment/front-despacho